version: '3.8'
services:
  db:
    image: mysql
    container_name: fit-finance_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - fit-finance_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-fit-finance
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus.yml"
    ports:
      - "9090:9090"

volumes:
  fit-finance_data: