version: '2.7'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://fit_finance_mysql:3306/fit_finance?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

services:
  db:
    image: mysql
    container_name: fit_finance_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - fit-finance_data:/var/lib/mysql
    mem_limit: 512m

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-fit-finance
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus.yml"
    command: "--config.file=/etc/prometheus.yml"
    ports:
      - "9090:9090"
    mem_limit: 128m

  fit-finance-backend:
    image: patrickviolin/fit-finance-backend:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      <<: *database-variables
    mem_limit: 512m
    depends_on:
      - db

volumes:
  fit-finance_data: