version: '2.7'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - fit-finance_data:/var/lib/mysql
    mem_limit: 512m
    networks:
      fit-finance-network:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus.yml"
    command: "--config.file=/etc/prometheus.yml"
    ports:
      - "9090:9090"
    mem_limit: 128m
    networks:
      fit-finance-network:

  fit-finance-backend:
    image: patrickviolin/fit-finance-backend:latest
    container_name: fit-finance-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fit_finance?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    mem_limit: 512m
    networks:
      fit-finance-network:
    depends_on:
      - mysql
    restart: on-failure

volumes:
  fit-finance_data:

networks:
  fit-finance-network:
  default:
    driver: bridge
    external: true